### ISSUE TITLE
Ссылка на бинарник для Firefox ведет вникуда

### ISSUE THREAD

**Issue by nan0desu** [Rpsl/leprosorium#58]
Вот эта:
https://github.com/Rpsl/leprosorium/raw/master/__COMPILED_EXTENSIONS/leprosorium_0.8.xpi

**Comment by nan0desu** [comment]
Отзываю свой комментарий ab28daf5c8899662d53cc19f3b171d6e9d07ea4f

**Comment by Rpsl** [comment]
всё верно, я там на лепре, в посте про приложение писал ахтунги что версия 0.8 оказалась поломанной на платформе ff, поэтому бинарник был удален.

https://leprosorium.ru/comments/1724504/

парни вроде починили всё, на днях проверю и если всё ок, то будет сразу 0.8.1
