### ISSUE TITLE
Всё сломалось

### ISSUE THREAD

**Issue by nikitabegun** [Rpsl/leprosorium#62]
Народ, а только у меня всё поломалось?

![Capture](https://user-images.githubusercontent.com/32863129/83726408-2794a600-a64c-11ea-9435-be03289b8b57.PNG)

**Comment by Rpsl** [comment]
Я удивлен что им еще кто-то пользуется, но ради интереса пошел и проверил. 
У меня кнопка работает и показывает цифры. Проверь что ты авторизован на сайте и что у тебя открывается https://leprosorium.ru/ajax/api/lepropanel

**Comment by nikitabegun** [comment]
Увы. Много лет пользуюсь, суперудобно. А появилось что-то более новое и хорошее?

![Capture](https://user-images.githubusercontent.com/32863129/83727021-15673780-a64d-11ea-8184-a76218a50dc5.PNG)

**Comment by Rpsl** [comment]
> А появилось что-то более новое и хорошее?

%шутка про пикабу и реддит%

--
Не могу ответить, т.к. не слежу за сайтом, как и за другими плагинами.
